class_name MissionManifest
extends "res://scripts/resources/core/wcs_base_resource.gd"

## Mission Manifest Resource
##
## Stores metadata and asset references for a converted Wing Commander Saga mission.
## This resource is generated by the MissionConverter.

@export var mission_id: String = ""
@export var mission_name: String = ""
@export var source_file: String = ""

# Full Mission Data
@export var metadata: Dictionary = {}
@export var objects: Array[MissionObject] = []
@export var wings: Array[MissionWing] = []
@export var events: Array[MissionEvent] = []
@export var messages: Array[MissionMessage] = []
@export var briefing: BriefingData = BriefingData.new()
@export var debriefing: DebriefingData = DebriefingData.new()
@export var command_briefing: Array[CommandBriefingStage] = []

# Asset Dependencies
@export var cutscenes: Array[VideoStream] = [] # List of video streams
@export var audio: Array[Dictionary] = [] # { "path": "...", "usage": "..." }
@export var animations: Array[Dictionary] = [] # { "path": "...", "usage": "..." }
@export var models: Array[Dictionary] = [] # { "path": "...", "usage": "..." }

## List of fiction/text files
@export var fiction: Array[Dictionary] = [] # { "path": "...", "usage": "..." }

# === LOGIC & ENVIRONMENT ===
@export var sexp_variables: Array[SexpVariable] = []
@export var players: PlayerData = PlayerData.new()
@export var backgrounds: BackgroundData = BackgroundData.new()
@export var asteroid_fields: Array[AsteroidField] = []

func get_resource_type() -> String:
	return "mission_manifest"
