class_name MissionManifest
extends WCSBaseResource

## Mission Manifest Resource
##
## Stores metadata and asset references for a converted Wing Commander Saga mission.
## This resource is generated by the MissionConverter.

@export var mission_id: String = ""
@export var mission_name: String = ""
@export var source_file: String = ""

# Full Mission Data (Data-only, no logic)
@export var metadata: Dictionary = {}
@export var objects: Array[Dictionary] = []
@export var wings: Array[Dictionary] = []
@export var events: Array[Dictionary] = []
@export var messages: Array[Dictionary] = []
@export var briefing: Dictionary = {}
@export var debriefing: Dictionary = {}
@export var command_briefing: Array[Dictionary] = []

# Asset Dependencies
@export var cutscenes: Array[Dictionary] = [] # { "path": "...", "type": "briefing|command" }
@export var audio: Array[Dictionary] = [] # { "path": "...", "usage": "..." }
@export var animations: Array[Dictionary] = [] # { "path": "...", "usage": "..." }
@export var models: Array[Dictionary] = [] # { "path": "...", "usage": "..." }

## List of fiction/text files
@export var fiction: Array[Dictionary] = [] # { "path": "...", "usage": "..." }

func get_resource_type() -> String:
	return "mission_manifest"
