class_name MissionEnums

enum Team {
	FRIENDLY = 0,
	HOSTILE = 1,
	NEUTRAL = 2,
	UNKNOWN = 3,
	TRAITOR = 4,
	# Add others as needed
}

enum ArrivalLocation {
	HYPERSPACE = 0,
	NEAR_SHIP = 1,
	IN_FRONT_OF_SHIP = 2,
	DOCKING_BAY = 3,
	# Special cases might be handled separately or mapped here
}

enum DepartureLocation {
	HYPERSPACE = 0,
	DOCKING_BAY = 1,
}

enum AIBehavior {
	NONE = 0,
	CHASE = 1,
	EVADE = 2,
	GET_BEHIND = 3,
	STAY_NEAR = 4,
	STILL = 5,
	GUARD = 6,
	AVOID = 7,
	WAYPOINTS = 8,
	DOCK = 9,
	NONE_NOW = 10,
	BIG_SHIP = 11,
	PATH = 12,
	BEAM_TURRETS = 13,
	BAY_EMERGE = 14,
	BAY_DEPART = 15,
	SENTRY_GUN = 16,
	WARP_OUT = 17,
}

enum ShipFlags {
	CARGO_KNOWN = 0,
	IGNORE_COUNT = 1,
	PROTECT_SHIP = 2,
	REINFORCEMENT = 3,
	NO_SHIELDS = 4,
	ESCORT = 5,
	PLAYER_START = 6,
	NO_ARRIVAL_MUSIC = 7,
	NO_ARRIVAL_WARP = 8,
	NO_DEPARTURE_WARP = 9,
	LOCKED = 10,
	INVULNERABLE = 11,
	HIDDEN_FROM_SENSORS = 12,
	SCANNABLE = 13,
	KAMIKAZE = 14,
	NO_DYNAMIC = 15,
	RED_ALERT_CARRY = 16,
	BEAM_PROTECT_SHIP = 17,
	GUARDIAN = 18,
	SPECIAL_WARP = 19,
	VAPORIZE = 20,
	STEALTH = 21,
	FRIENDLY_STEALTH_INVISIBLE = 22,
	DONT_COLLIDE_INVISIBLE = 23,
	UNKNOWN = 24
}

enum ShipFlags2 {
	PRIMITIVE_SENSORS = 0,
	NO_SUBSPACE_DRIVE = 1,
	NAV_CARRY_STATUS = 2,
	AFFECTED_BY_GRAVITY = 3,
	TOGGLE_SUBSYSTEM_SCANNING = 4,
	TARGETABLE_AS_BOMB = 5,
	NO_BUILTIN_MESSAGES = 6,
	PRIMARIES_LOCKED = 7,
	SECONDARIES_LOCKED = 8,
	NO_DEATH_SCREAM = 9,
	ALWAYS_DEATH_SCREAM = 10,
	NAV_NEEDSLINK = 11,
	HIDE_SHIP_NAME = 12,
	SET_CLASS_DYNAMICALLY = 13,
	LOCK_ALL_TURRETS = 14,
	AFTERBURNERS_LOCKED = 15,
	FORCE_SHIELDS_ON = 16,
	HIDE_LOG_ENTRIES = 17,
	NO_ARRIVAL_LOG = 18,
	NO_DEPARTURE_LOG = 19,
	IS_HARMLESS = 20,
	UNKNOWN = 21
}

enum OrdersAccepted {
	ATTACK_TARGET = 0,
	DISABLE_TARGET = 1,
	DISARM_TARGET = 2,
	PROTECT_TARGET = 3,
	IGNORE_TARGET = 4,
	FORMATION = 5,
	COVER_ME = 6,
	ENGAGE_ENEMY = 7,
	CAPTURE_TARGET = 8,
	REARM_REPAIR_ME = 9,
	ABORT_REARM_REPAIR = 10,
	STAY_NEAR_ME = 11,
	STAY_NEAR_TARGET = 12,
	KEEP_SAFE_DIST = 13,
	DEPART = 14,
	DISABLE_SUBSYSTEM = 15,
	UNKNOWN = 16
}

enum GameTypeFlags {
	SINGLE = 0,
	MULTI = 1,
	TRAINING = 2,
	MULTI_COOP = 3,
	MULTI_TEAMS = 4,
	MULTI_DOGFIGHT = 5,
	UNKNOWN = 6
}

enum MissionFlags {
	SUBSPACE = 0,
	NO_PROMOTION = 1,
	FULLNEB = 2,
	NO_BUILTIN_MSGS = 3,
	NO_TRAITOR = 4,
	TOGGLE_SHIP_TRAILS = 5,
	SUPPORT_REPAIRS_HULL = 6,
	BEAM_FREE_ALL_BY_DEFAULT = 7,
	NO_BRIEFING = 8,
	TOGGLE_DEBRIEFING = 9,
	ALLOW_DOCK_TREES = 10,
	MISSION_2D = 11,
	RED_ALERT = 12,
	SCRAMBLE = 13,
	NO_BUILTIN_COMMAND = 14,
	PLAYER_START_AI = 15,
	ALL_ATTACK = 16,
	USE_AP_CINEMATICS = 17,
	DEACTIVATE_AP = 18,
	UNKNOWN = 19
}

enum SkyboxFlags {
	SHOW_OUTLINE = 0,
	SHOW_PIVOTS = 1,
	SHOW_PATHS = 2,
	SHOW_RADIUS = 3,
	SHOW_SHIELDS = 4,
	SHOW_THRUSTERS = 5,
	LOCK_DETAIL = 6,
	NO_POLYS = 7,
	NO_LIGHTING = 8,
	NO_TEXTURING = 9,
	NO_CORRECT = 10,
	NO_SMOOTHING = 11,
	IS_ASTEROID = 12,
	IS_MISSILE = 13,
	SHOW_OUTLINE_PRESET = 14,
	SHOW_INVISIBLE_FACES = 15,
	AUTOCENTER = 16,
	BAY_PATHS = 17,
	ALL_XPARENT = 18,
	NO_ZBUFFER = 19,
	NO_CULL = 20,
	FORCE_TEXTURE = 21,
	FORCE_LOWER_DETAIL = 22,
	EDGE_ALPHA = 23,
	CENTER_ALPHA = 24,
	NO_FOGGING = 25,
	SHOW_OUTLINE_HTL = 26,
	UNKNOWN = 27
}
