class_name MissionManifest
extends Resource

## Mission Manifest Resource
##
## Stores metadata and asset references for a converted Wing Commander Saga mission.
## This resource is generated by the MissionConverter.

@export_group("Metadata")
@export var mission_id: String = ""
@export var mission_name: String = ""
@export var source_file: String = ""

@export_group("Assets")
## List of cutscenes used in the mission
@export var cutscenes: Array[Dictionary] = [] # { "path": "...", "type": "briefing|command" }

## List of audio files (music, voice)
@export var audio: Array[Dictionary] = [] # { "path": "...", "usage": "..." }

## List of animations (.ani/.eff)
@export var animations: Array[Dictionary] = [] # { "path": "...", "usage": "..." }

## List of models (skybox, etc)
@export var models: Array[Dictionary] = [] # { "path": "...", "usage": "..." }

## List of fiction/text files
@export var fiction: Array[Dictionary] = [] # { "path": "...", "usage": "..." }
