class_name CampaignManifest
extends "res://scripts/resources/core/wcs_base_resource.gd"

## Campaign Manifest Resource
##
## Stores metadata and mission progression for a Wing Commander Saga campaign.
## This resource is generated by the CampaignConverter.
const CampaignMission = preload("res://scripts/resources/campaigns/campaign_mission.gd")
const MissionEnums = preload("res://scripts/resources/missions/mission_enums.gd")
# === METADATA ===
@export_group("Metadata", "meta_")
@export var campaign_name: String = ""
@export var campaign_type: String = "single"  # single, multi
@export var description: String = ""
@export var author: String = ""

# === MEDIA ===
@export_group("Media", "media_")
@export var intro_cutscene: Resource  # VideoStream or AudioStream
@export var end_cutscene: Resource  # VideoStream or AudioStream
@export var description_anim: Resource  # VideoStream or other anim resource

# === CONFIGURATION ===
@export_group("Configuration", "config_")
@export var starting_ships: Array[Resource] = []  # List of allowed ships (ShipStats)
@export var starting_weapons: Array[Resource] = []  # List of allowed weapons (WeaponData)
@export var loop_mission: bool = false
@export var flags: Array[MissionEnums.CampaignFlags] = []  # Campaign flags

# === MISSIONS ===
@export_group("Missions", "mission_")
@export var missions: Array[CampaignMission] = []


func get_resource_type() -> String:
	return "campaign_manifest"
