class_name ShipModelData
extends Resource
"""
Stores spatial data extracted from the ship's 3D model (POF).
This includes hardpoints for weapons, thrusters, eyes, and subsystem bounding boxes.
This resource is generated by the conversion pipeline and linked to ShipStats.
"""

# --- Weapon Hardpoints ---
# Guns and Missiles are organized in banks.
@export var guns: Array[ShipHardpointBank] = []
@export var missiles: Array[ShipHardpointBank] = []

# --- Turrets ---
@export var turrets: Array[ShipTurret] = []

# --- Thrusters ---
@export var thrusters: Array[ShipThruster] = []

# --- View Positions ---
@export var eyes: Array[ShipEye] = []

# --- Subsystem Spatial Data ---
@export var subsystems: Array[ShipSubsystem] = []

# --- Metadata ---
@export var source_file: String = "" # Original POF filename
@export var generated_timestamp: String = ""


func get_gun_bank_points(bank_name: String) -> Array[Vector3]:
	for bank in guns:
		if bank.name == bank_name:
			return bank.points
	return []

func get_missile_bank_points(bank_name: String) -> Array[Vector3]:
	for bank in missiles:
		if bank.name == bank_name:
			return bank.points
	return []

func get_subsystem_center(subsystem_name: String) -> Vector3:
	for sub in subsystems:
		if sub.name == subsystem_name:
			return sub.center
	return Vector3.ZERO
